name: Deploy to S3 & CloudFront

on:
  push:
    branches: 
    - dev-pipeline
    - develop
    - main
  workflow_dispatch:

jobs:
  deploy_to_s3:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
         aws-region: ${{ vars.AWS_REGION }}

      - name: Checkout Wagtail repository
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.WAGTAIL_REPO }}
          ref: develop/landing-page
          token: ${{ secrets.WAGTAIL_TOKEN }}
          path: wagtail-source

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Wagtail dependencies
        run: |
          cd wagtail-source
          pip install -r requirements.txt

      - name: Collect static files from Wagtail
        run: |
          cd wagtail-source
          python manage.py collectstatic --noinput

      - name: Sync static files to Static bucket
        run: |
          aws s3 sync wagtail-source/staticfiles/ s3://${{ vars.S3_STATIC_BUCKET_NAME }}/ --delete
          echo "✅ Static files synced to Static bucket"

      - name: Sync media files to Media bucket
        run: |
          aws s3 sync wagtail-source/media/ s3://${{ vars.S3_MEDIA_BUCKET_NAME }}/ --delete
          echo "✅ Media files synced to Media bucket"

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
          echo "✅ CloudFront cache invalidated"

      - name: Success message
        run: |
          echo "🚀 Deployment completed successfully!"
          echo "📁 Static files uploaded to: ${{ vars.S3_STATIC_BUCKET_NAME }}"
          echo "📁 Media files uploaded to: ${{ vars.S3_MEDIA_BUCKET_NAME }}"
          echo "☁️ CloudFront updated: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}"
